libft: libft.h File Reference
libft.h File Reference
#include <string.h>
Data Structures
struct s_list
Typedefs
typedef struct s_list t_list
Functions
int ft_abs (int a)
int ft_atoi (const char *str)
void ft_bzero (void *s, size_t n)
int ft_isalnum (int c)
int ft_isalpha (int c)
int ft_isascii (int c)
int ft_isdigit (int c)
int ft_isprint (int c)
int ft_isspace (int c)
char * ft_itoa (int n)
void ft_lstadd (t_list **alst, t_list *new)
void ft_lstappend (t_list **alst, t_list *new)
void ft_lstdel (t_list **alst, void(*del)(void *, size_t))
void ft_lstdelone (t_list **alst, void(*del)(void *, size_t))
void ft_lstiter (t_list *lst, void(*f)(t_list *elem))
t_list * ft_lstlast (t_list *head)
t_list * ft_lstmap (t_list *lst, t_list *(*f)(t_list *elem))
t_list * ft_lstnew (void const *content, size_t content_size)
int ft_max (int a, int b)
void * ft_memalloc (size_t size)
void * ft_memccpy (void *dst, const void *src, int c, size_t n)
void * ft_memchr (const void *s, int c, size_t n)
int ft_memcmp (const void *s1, const void *s2, size_t n)
void * ft_memcpy (void *dst, const void *src, size_t n)
void ft_memdel (void **ap)
void * ft_memmove (void *dst, const void *src, size_t n)
void * ft_memset (void *b, int c, size_t len)
int ft_min (int a, int b)
int ft_power (int num, unsigned int exponent)
void ft_putchar (char c)
void ft_putchar_fd (char c, int fd)
void ft_putendl (char const *s)
void ft_putendl_fd (char const *s, int fd)
void ft_putnbr (int n)
void ft_putnbr_fd (int n, int fd)
void ft_putnstr (char *s, size_t n)
void ft_putnstr_fd (char *s, size_t n, int fd)
void ft_putstr (char const *s)
void ft_putstr_fd (char const *s, int fd)
int ft_sqrt (int num)
char * ft_strcapitalize (const char *str)
char * ft_strcat (char *s1, const char *s2)
int ft_strcchr (char const *str, char c)
char * ft_strchr (const char *s, int c)
void ft_strclr (char *s)
int ft_strcmp (const char *s1, const char *s2)
char * ft_strcpy (char *dst, const char *src)
void ft_strdel (char **as)
char * ft_strdup (const char *s1)
int ft_strequ (const char *s1, const char *s2)
int ft_strintab (const char *str, char *const tab[])
void ft_striter (char *s, void(*f)(char *))
void ft_striteri (char *s, void(*f)(unsigned int, char *))
char * ft_strjoin (const char *s1, const char *s2)
char ft_strlast (char const *str)
size_t ft_strlcat (char *dst, const char *src, size_t dstsize)
size_t ft_strlcpy (char *dst, const char *src, size_t maxlen)
size_t ft_strlen (const char *s)
char * ft_strmap (char const *s, char(*f)(char))
char * ft_strmapi (char const *s, char(*f)(unsigned int, char))
char * ft_strncat (char *s1, const char *s2, size_t n)
int ft_strncmp (const char *s1, const char *s2, size_t n)
char * ft_strncpy (char *dst, const char *src, size_t len)
char * ft_strndup (const char *s1, size_t len)
int ft_strnequ (char const *s1, char const *s2, size_t n)
char * ft_strnew (size_t size)
char * ft_strnstr (const char *haystack, const char *needle, size_t len)
char * ft_strrchr (const char *s, int c)
char * ft_strrev (const char *s)
char ** ft_strsplit (char const *str, char delim)
char * ft_strstr (const char *haystack, const char *needle)
char * ft_strsub (char const *s, unsigned int start, size_t len)
char * ft_strtrim (char const *s)
int ft_tolower (int c)
int ft_toupper (int c)
Function Documentation
ft_abs()
int ft_abs (int a) inline
Returns the absolute value of the argument.
Note
This function is only needed, since "The Norme" (the code standard at School 42) forbids the use of parametrized macros; hence this is an inline function.
Parameters
[in] a The integer to take an absolute value of.
Definition at line 21 of file ft_abs.c.
 {
     return (a < 0 ? -a : a);
 }
ft_atoi()
int ft_atoi (const char * str)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 20 of file ft_atoi.c.
 {
     int         i;
     int         num;
     int         is_neg;
     i = 0;
     is_neg = 0;
     num = 0;
     while (str[i] == ' ' || str[i] == '\t' || str[i] == '\n' || str[i] == '\v'
     || str[i] == '\f' || str[i] == '\r')
         i++;
     if (str[i] == '-')
         is_neg = 1;
     if (str[i] == '-' || str[i] == '+')
         i++;
     while (str[i] >= '0' && str[i] <= '9')
     {
         num *= 10;
         num += (str[i] - '0');
         i++;
     }
     return (is_neg ? -num : num);
 }
ft_bzero()
void ft_bzero (void * s, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_bzero.c.
 {
     size_t          i;
     unsigned char   *s1;
     i = 0;
     s1 = (unsigned char *)s;
     while (i < n)
         s1[i++] = 0;
 }
ft_isalnum()
int ft_isalnum (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isalnum.c.
 {
     return (ft_isalpha(c) || ft_isdigit(c));
 }
References ft_isalpha(), and ft_isdigit().
ft_isalpha()
int ft_isalpha (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isalpha.c.
 {
     if (c >= 'a' && c <= 'z')
         return (1);
     else if (c >= 'A' && c <= 'Z')
         return (1);
     else
         return (0);
 }
Referenced by ft_isalnum().
ft_isascii()
int ft_isascii (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isascii.c.
 {
     return (c >= 0 && c <= 127);
 }
ft_isdigit()
int ft_isdigit (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isdigit.c.
 {
     if (c >= '0' && c <= '9')
         return (1);
     else
         return (0);
 }
Referenced by ft_isalnum().
ft_isprint()
int ft_isprint (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isprint.c.
 {
     return (c >= 040 && c <= 0176);
 }
ft_isspace()
int ft_isspace (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_isspace.c.
 {
     return ((c >= 9 && c <= 13) || c == ' ');
 }
ft_itoa()
char* ft_itoa (int n)
Allocate (with malloc) and returns a fresh string ending with '\0' representing the integer n given as argument. Negative numbers must be supported. If the allocation fails, the function returns NULL.
Parameters
n The integer to be transformed into a string.
Returns
The string representing the integer passed as argument.
Definition at line 52 of file ft_itoa.c.
 {
     char    *str;
     size_t  len;
     int     tmp;
     len = ft_len(n);
     tmp = n;
     if (n == INT_MIN)
         return (ft_itoa_intmin(n));
     if (n < 0)
     {
         tmp = -n;
         len++;
     }
     if (!(str = ft_strnew(len)))
         return (NULL);
     str[--len] = tmp % 10 + '0';
     while (tmp /= 10)
         str[--len] = tmp % 10 + '0';
     if (n < 0)
         str[--len] = '-';
     return (str);
 }
References ft_strnew().
ft_lstadd()
void ft_lstadd (t_list ** alst, t_list * new)
Adds the element new at the beginning of the list.
Parameters
alst The address of a pointer to the first link of a list.
new The link to add at the beginning of the list.
Definition at line 21 of file ft_lstadd.c.
 {
     if (!alst || !new)
         return ;
     new->next = *alst;
     *alst = new;
 }
ft_lstappend()
void ft_lstappend (t_list ** alst, t_list * new)
Adds the element new at the end of the list.
Parameters
alst The address of a pointer to the first link of a list.
new The link to add at the beginning of the list.
Definition at line 21 of file ft_lstappend.c.
 {
     t_list  *last;
     if (!alst || !new)
         return ;
     if (!*alst)
     {
         *alst = new;
         return ;
     }
     last = ft_lstlast(*alst);
     last->next = new;
 }
References ft_lstlast(), and s_list::next.
ft_lstdel()
void ft_lstdel (t_list ** alst, void(*)(void *, size_t) del)
Takes as a parameter the address of a pointer to a link and frees the memory of this link and every successors of that link using the functions del and free. Finally the pointer to the link that was just freed must be set to NULL (quite similar to the function memdel).
Parameters
alst The address of a pointer to the first link of a list that needs to be freed.
del The address of a function to apply to each link of a list.
Definition at line 27 of file ft_lstdel.c.
 {
     t_list *head;
     t_list *new_head;
     if (!alst || !(*alst) || !del)
         return ;
     head = *alst;
     while (head)
     {
         new_head = head->next;
         del(head->content, head->content_size);
         free(head);
         head = new_head;
     }
     *alst = NULL;
 }
References s_list::content, s_list::content_size, and s_list::next.
ft_lstdelone()
void ft_lstdelone (t_list ** alst, void(*)(void *, size_t) del)
Takes as a parameter a links pointer address and frees the memory of the links content using the function del given as a parameter, then frees the links memory using free. The memory of next must not be freed under any circumstance. Finally, the pointer to the link that was just freed must be set to NULL (quite similar to the function memdel).
Parameters
alst The adress of a pointer to a link that needs to be freed.
del The address of a function to apply to each link of a list.
Definition at line 27 of file ft_lstdelone.c.
 {
     t_list  *link;
     if (!alst || !(*alst) || !del || !(*del))
         return ;
     link = *alst;
     link->next = NULL;
     del(link->content, link->content_size);
     free(link);
     *alst = NULL;
 }
References s_list::content, s_list::content_size, and s_list::next.
ft_lstiter()
void ft_lstiter (t_list * lst, void(*)(t_list *elem) f)
Iterates the list lst and applies the function f to each link.
Parameters
lst A pointer to the first link of a list.
f The address of a function to apply to each link of a list.
Definition at line 21 of file ft_lstiter.c.
 {
     if (!f)
         return ;
     while (lst)
     {
         f(lst);
         lst = lst->next;
     }
 }
References s_list::next.
ft_lstlast()
t_list* ft_lstlast (t_list * lst)
Return last element of the list.
Parameters
lst A pointers to the first link of a list.
Returns
The last link of the list.
Definition at line 21 of file ft_lstlast.c.
 {
     if (!lst)
         return (NULL);
     while (lst->next)
         lst = lst->next;
     return (lst);
 }
References s_list::next.
Referenced by ft_lstappend().
ft_lstmap()
t_list* ft_lstmap (t_list * lst, t_list *(*)(t_list *elem) f)
Iterates a list lst and applies the function f to each link to create a fresh list (using malloc) resulting from the successive applications of f. If the allocation fails, the function returns NULL.
Parameters
lst A pointers to the first link of a list.
f The address of a function to apply to each link of a list.
Returns
The new list.
Remarks
This function fails if f returns NULL;
Definition at line 26 of file ft_lstmap.c.
 {
     t_list  *new;
     t_list  *tmp;
     if (!lst)
         return (NULL);
     tmp = f(lst);
     new = tmp;
     while (lst->next)
     {
         lst = lst->next;
         tmp->next = f(lst);
         tmp = tmp->next;
     }
     return (new);
 }
References s_list::next.
ft_lstnew()
t_list* ft_lstnew (void const * content, size_t content_size)
Allocates (with malloc) and returns a fresh link. The variables content and content_size of the new link are initialized by copy of the parameters of the function. If the parameter content is NULL, the variable content is initialized to NULL and the variable content_size is initialized to 0 even if the parameter content_size isnt. The variable next is initialized to NULL. If the allocation fails, the function returns NULL.
Parameters
content The content to put in the new link.
content_size The size of the content of the new link.
Returns
The new link.
Definition at line 29 of file ft_lstnew.c.
 {
     t_list  *link;
     if (!(link = (t_list *)malloc(sizeof(t_list))))
         return (NULL);
     if (content)
     {
         if (!(link->content = ft_memalloc(content_size)))
         {
             ft_memdel((void **)&link);
             return (NULL);
         }
         ft_memcpy(link->content, content, content_size);
         link->content_size = content_size;
     }
     else
     {
         link->content = NULL;
         link->content_size = 0;
     }
     link->next = NULL;
     return (link);
 }
References s_list::content, s_list::content_size, ft_memalloc(), ft_memcpy(), ft_memdel(), and s_list::next.
ft_max()
int ft_max (int a, int b) inline
Returns the maximum of two integer arguments.
Note
This function is only needed, since "The Norme" (the code standard at School 42) forbids the use of parametrized macros; hence this is an inline function.
Parameters
[in] a The first integer to compare.
[in] b The second integer to compare.
Returns
The larger of the two integers.
Definition at line 23 of file ft_max.c.
 {
     return (a > b ? a : b);
 }
ft_memalloc()
void* ft_memalloc (size_t size)
Allocates (with malloc) and returns a fresh memory area. The memory allocated is initialized to 0. If the allocation fails, the function returns NULL.
Parameters
size The size of the memory that needs to be allocated.
Returns
The allocated memory area.
Definition at line 24 of file ft_memalloc.c.
 {
     char    *mem;
     mem = malloc(size);
     if (mem == NULL)
         return (NULL);
     ft_memset(mem, 0, size);
     return (mem);
 }
References ft_memset().
Referenced by ft_lstnew(), ft_strnew(), and ft_strsplit().
ft_memccpy()
void* ft_memccpy (void * dst, const void * src, int c, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memccpy.c.
 {
     size_t          i;
     unsigned char   *s1;
     unsigned char   *s2;
     unsigned char   c1;
     s1 = (unsigned char *)dst;
     s2 = (unsigned char *)src;
     c1 = (unsigned char)c;
     i = 0;
     while (i < n)
     {
         s1[i] = s2[i];
         if (s1[i] == c1)
             return (s1 + i + 1);
         i++;
     }
     return (NULL);
 }
ft_memchr()
void* ft_memchr (const void * s, int c, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memchr.c.
 {
     size_t          i;
     unsigned char   *s1;
     unsigned char   c1;
     i = 0;
     s1 = (unsigned char *)s;
     c1 = (unsigned char)c;
     while (i < n)
     {
         if (s1[i] == c1)
             return (s1 + i);
         i++;
     }
     return (NULL);
 }
ft_memcmp()
int ft_memcmp (const void * s1, const void * s2, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memcmp.c.
 {
     unsigned char   *str1;
     unsigned char   *str2;
     size_t          i;
     i = 0;
     str1 = (unsigned char *)s1;
     str2 = (unsigned char *)s2;
     while (i < n)
     {
         if (str1[i] - str2[i])
             return (str1[i] - str2[i]);
         i++;
     }
     return (0);
 }
ft_memcpy()
void* ft_memcpy (void * dst, const void * src, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memcpy.c.
 {
     size_t          i;
     unsigned char   *dst1;
     unsigned char   *src1;
     if (!dst && !src)
         return (NULL);
     i = 0;
     dst1 = (unsigned char *)dst;
     src1 = (unsigned char *)src;
     while (i < n)
     {
         dst1[i] = src1[i];
         i++;
     }
     return (dst);
 }
Referenced by ft_lstnew(), and ft_strlcpy().
ft_memdel()
void ft_memdel (void ** ap)
Takes as a parameter the address of a memory area that needs to be freed with free, then puts the pointer to NULL.
Parameters
ap A pointers address that needs its memory freed and set to NULL.
Definition at line 22 of file ft_memdel.c.
 {
     if (!ap || !(*ap))
         return ;
     free(*ap);
     *ap = 0;
 }
Referenced by ft_lstnew(), and ft_strdel().
ft_memmove()
void* ft_memmove (void * dst, const void * src, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memmove.c.
 {
     unsigned char   *s1;
     unsigned char   *s2;
     if (!dst && !src)
         return (NULL);
     s1 = (unsigned char *)dst;
     s2 = (unsigned char *)src;
     while (n > 0)
     {
         if (s1 < s2)
             *(s1++) = *(s2++);
         else
             s1[n - 1] = s2[n - 1];
         n--;
     }
     return (dst);
 }
ft_memset()
void* ft_memset (void * b, int c, size_t len)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_memset.c.
 {
     unsigned char   *s;
     unsigned char   c1;
     s = (unsigned char *)b;
     c1 = (unsigned char)c;
     while (len-- > 0)
     {
         *s = c;
         s++;
     }
     return (b);
 }
Referenced by ft_memalloc(), and ft_strclr().
ft_min()
int ft_min (int a, int b) inline
Returns the minimum of two integer arguments.
Note
This function is only needed, since "The Norme" (the code standard at School 42) forbids the use of parametrized macros; hence this is an inline function.
Parameters
[in] a The first integer to compare.
[in] b The second integer to compare.
Returns
The smaller of the two integers.
Definition at line 23 of file ft_min.c.
 {
     return (a < b ? a : b);
 }
ft_power()
int ft_power (int num, unsigned int exponent)
Raises a number to a given power.
Parameters
num The base.
exponent The exponent.
Returns
The result or 0 if an integer overflow occurred.
Definition at line 23 of file ft_power.c.
 {
     long long result;
     result = 1;
     while (exponent-- > 0)
         result *= num;
     if (result > INT_MAX)
         return (0);
     else
         return ((int)result);
 }
ft_putchar()
void ft_putchar (char c)
Outputs the character c to the standard output.
Parameters
c The character to output.
Definition at line 21 of file ft_putchar.c.
 {
     ft_putchar_fd(c, 1);
 }
References ft_putchar_fd().
ft_putchar_fd()
void ft_putchar_fd (char c, int fd)
Outputs the char c to the file descriptor fd.
Parameters
c The character to output.
fd The file descriptor.
Definition at line 22 of file ft_putchar_fd.c.
 {
     write(fd, &c, 1);
 }
Referenced by ft_putchar(), ft_putendl_fd(), and ft_putnbr_fd().
ft_putendl()
void ft_putendl (char const * s)
Outputs the string s to the standard output followed by a '\n'.
Parameters
s The string to output.
Definition at line 20 of file ft_putendl.c.
 {
     ft_putendl_fd(s, 1);
 }
References ft_putendl_fd().
ft_putendl_fd()
void ft_putendl_fd (char const * s, int fd)
Outputs the string s to the file descriptor fd followed by a '\n'.
Parameters
s The string to output.
fd The file descriptor.
Definition at line 21 of file ft_putendl_fd.c.
 {
     ft_putstr_fd(s, fd);
     ft_putchar_fd('\n', fd);
 }
References ft_putchar_fd(), and ft_putstr_fd().
Referenced by ft_putendl().
ft_putnbr()
void ft_putnbr (int n)
Outputs the integer n to the standard output.
Parameters
n The integer to output.
Definition at line 20 of file ft_putnbr.c.
 {
     ft_putnbr_fd(n, 1);
 }
References ft_putnbr_fd().
ft_putnbr_fd()
void ft_putnbr_fd (int n, int fd)
Outputs the integer n to the file descriptor fd.
Parameters
n The integer to print.
fd The file descriptor.
Definition at line 22 of file ft_putnbr_fd.c.
 {
     if (n == INT_MIN)
     {
         ft_putnbr_fd(n / 10, fd);
         ft_putnbr_fd(-(n % 10), fd);
     }
     else if (n < 0)
     {
         ft_putchar_fd('-', fd);
         ft_putnbr_fd(-n, fd);
     }
     else if (n > 9)
     {
         ft_putnbr_fd(n / 10, fd);
         ft_putchar_fd(n % 10 + '0', fd);
     }
     else
         ft_putchar_fd(n % 10 + '0', fd);
 }
References ft_putchar_fd().
Referenced by ft_putnbr().
ft_putnstr()
void ft_putnstr (char * s, size_t n)
Outputs the first n characters of the string s to the standard output.
Parameters
s The string, the characters of which to output.
n The number of characters to output.
Remarks
If s contains less than n characters, behaviour is undefined.
Definition at line 23 of file ft_putnstr.c.
 {
     write(1, s, n);
 }
ft_putnstr_fd()
void ft_putnstr_fd (char * s, size_t n, int fd)
Outputs the first n characters of the string s to the file descriptor fd.
Parameters
s The string, the characters of which to output.
n The number of characters to output.
fd The file descriptor.
Remarks
If s contains less than n characters, behaviour is undefined.
Definition at line 24 of file ft_putnstr_fd.c.
 {
     write(fd, s, n);
 }
ft_putstr()
void ft_putstr (char const * s)
Outputs the string s to the standard output.
Parameters
s The string to output.
Definition at line 21 of file ft_putstr.c.
 {
     ft_putstr_fd(s, 1);
 }
References ft_putstr_fd().
ft_putstr_fd()
void ft_putstr_fd (char const * s, int fd)
Outputs the string s to the file descriptor fd.
Parameters
s The string to output.
fd The file descriptor.
Definition at line 22 of file ft_putstr_fd.c.
 {
     write(fd, s, ft_strlen(s));
 }
References ft_strlen().
Referenced by ft_putendl_fd(), and ft_putstr().
ft_sqrt()
int ft_sqrt (int num)
Computes an integer square root of a given number.
Parameters
num The number of which to take a square root.
Returns
The integer square root, or -1 if it doesn't exit.
Definition at line 19 of file ft_sqrt.c.
 {
     int factor;
     if (num < 0 ||
         (num % 2 == 0 && num % 4 != 0) ||
         (num % 3 == 0 && num % 9 != 0))
         return (-1);
     factor = (num % 2) ? 1 : 0;
     while (factor < num / 2)
     {
         if (factor * factor == num)
             return (factor);
         factor += 2;
     }
     return (-1);
 }
ft_strcapitalize()
char* ft_strcapitalize (const char * s1)
Capitalizes all words (defined as stretches of alpha-numeric characters) in a NULL-terminated string and writes them to a newly allocated string.
Example: ft_strcapitalize("My word IS 42about%8THEM") returns "My Word Is 42about%8them")
Parameters
s1 The string to capitalize.
Returns
A duplicate of str in which all words have been capitalized. If str is a NULL pointer or allocation fails, NULL is returned.
Definition at line 49 of file ft_strcapitalize.c.
 {
     char    *s2;
     if (!s1 || !(s2 = ft_strdup(s1)))
         return (0);
     while (scroll_to_word(&s2))
         capitalize_word(&s2);
     return (s2);
 }
References ft_strdup().
ft_strcat()
char* ft_strcat (char * s1, const char * s2)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strcat.c.
 {
     size_t  i;
     size_t  len;
     len = ft_strlen(s1);
     i = 0;
     while (s2[i])
     {
         s1[len + i] = s2[i];
         i++;
     }
     s1[len + i] = '\0';
     return (s1);
 }
References ft_strlen().
Referenced by ft_strjoin().
ft_strcchr()
int ft_strcchr (char const * str, char c)
Count the number of occurrences of a character in a string.
Parameters
str The string in which to search.
c The character for which to search.
Returns
The number of occurences.
Definition at line 22 of file ft_strcchr.c.
 {
     int count;
     count = 0;
     if (!str || !c)
         return (-1);
     while (*str)
     {
         if (*str == c)
             count++;
         str++;
     }
     return (count);
 }
ft_strchr()
char* ft_strchr (const char * s, int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strchr.c.
 {
     size_t  i;
     i = 0;
     while (s[i])
     {
         if (s[i] == c)
             return ((char *)(s + i));
         i++;
     }
     if (c == 0)
         return ((char *)(s + i));
     else
         return (NULL);
 }
ft_strclr()
void ft_strclr (char * s)
Sets every character of the string to the value '\0'.
Parameters
s The string that needs to be cleared.
Definition at line 20 of file ft_strclr.c.
 {
     if (!s)
         return ;
     ft_memset(s, 0, ft_strlen(s));
 }
References ft_memset(), and ft_strlen().
ft_strcmp()
int ft_strcmp (const char * s1, const char * s2)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strcmp.c.
 {
     unsigned char   *s1u;
     unsigned char   *s2u;
     s1u = (unsigned char *)s1;
     s2u = (unsigned char *)s2;
     while (*s1u || *s2u)
     {
         if (*s1u - *s2u)
             return (*s1u - *s2u);
         s1u++;
         s2u++;
     }
     return (0);
 }
ft_strcpy()
char* ft_strcpy (char * dst, const char * src)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strcpy.c.
 {
     size_t  i;
     i = 0;
     while (src[i])
     {
         dst[i] = src[i];
         i++;
     }
     dst[i] = 0;
     return (dst);
 }
Referenced by ft_strjoin().
ft_strdel()
void ft_strdel (char ** as)
Takes as a parameter the address of a string that need to be freed with free, then sets its pointer to NULL.
Parameters
as The strings address that needs to be freed and its pointer set to NULL.
Definition at line 22 of file ft_strdel.c.
 {
     ft_memdel((void **)as);
 }
References ft_memdel().
ft_strdup()
char* ft_strdup (const char * s1)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strdup.c.
 {
     size_t  i;
     char    *cpy;
     if (!(cpy = ft_strnew(ft_strlen(s1))))
         return (NULL);
     i = 0;
     while (s1[i])
     {
         cpy[i] = s1[i];
         i++;
     }
     cpy[i] = 0;
     return (cpy);
 }
References ft_strlen(), and ft_strnew().
Referenced by ft_strcapitalize(), ft_strmap(), ft_strmapi(), and ft_strtrim().
ft_strequ()
int ft_strequ (const char * s1, const char * s2)
Lexicographical comparison between s1 and s2 up to n characters or until a '\0' is reached. If the 2 strings are identical, the function returns 1, or 0 otherwise.
Parameters
s1 The first string to be compared.
s2 The second string to be compared.
Returns
1 or 0 according to if the 2 strings are identical or not.
Definition at line 24 of file ft_strequ.c.
 {
     if (!s1 && !s2)
         return (1);
     else if (!s1 || !s2)
         return (0);
     while (*s1 || *s2)
     {
         if (*s1 != *s2)
             return (0);
         s1++;
         s2++;
     }
     return (1);
 }
Referenced by ft_strintab().
ft_strintab()
int ft_strintab (const char * str, char *const tab[])
Perform lexicographical comparison between a given string and strings contained in a NULL-terminated tab. If the tab contains an identical string, the function returns 1, or 0 otherwise.
Parameters
str The string to search for.
tab The NULL-terminated tab to search in.
Returns
1 or 0 depending on whether the tab contains an identical string.
Definition at line 25 of file ft_strintab.c.
 {
     while (*tab)
     {
         if (ft_strequ(str, *tab))
             return (1);
         tab++;
     }
     return (0);
 }
References ft_strequ().
ft_striter()
void ft_striter (char * s, void(*)(char *) f)
Applies the function f to each character of the string passed as argument. Each character is passed by address to f to be modified if necessary.
Parameters
s The string to iterate.
f The function to apply to each character of s.
Definition at line 22 of file ft_striter.c.
 {
     if (!s || !f)
         return ;
     while (*s)
         f(s++);
 }
ft_striteri()
void ft_striteri (char * s, void(*)(unsigned int, char *) f)
Applies the function f to each character of the string passed as argument, and passing its index as first argument. Each character is passed by address to f to be modified if necessary.
Parameters
s The string to iterate.
f The function to apply to each character of s and its index.
Definition at line 23 of file ft_striteri.c.
 {
     size_t  i;
     if (!s || !f)
         return ;
     i = 0;
     while (*s)
         f(i++, s++);
 }
ft_strjoin()
char* ft_strjoin (const char * s1, const char * s2)
Allocates (with malloc) and returns a fresh string ending with '\0', result of the concatenation of s1 and s2. If the allocation fails the function returns NULL.
Parameters
s1 The prefix string.
s2 The suffix string.
Returns
The fresh string result of the concatenation of the 2 strings.
Definition at line 24 of file ft_strjoin.c.
 {
     char    *s_joined;
     if (!s1 && !s2)
         return (NULL);
     else if (!s1)
         return (char *)s2;
     else if (!s2)
         return (char *)s1;
     if (!(s_joined = ft_strnew(ft_strlen(s1) + ft_strlen(s2))))
         return (NULL);
     s_joined = ft_strcpy(s_joined, s1);
     s_joined = ft_strcat(s_joined, s2);
     return (s_joined);
 }
References ft_strcat(), ft_strcpy(), ft_strlen(), and ft_strnew().
ft_strlast()
char ft_strlast (char const * str)
Returns the last characters (excluding NULL-termination) of a string.
Parameters
str The string.
Returns
The last character of the string, or 0 if it is empty.
Definition at line 21 of file ft_strlast.c.
 {
     size_t  i;
     i = 0;
     while (str[i + 1])
         i++;
     return (str[i]);
 }
ft_strlcat()
size_t ft_strlcat (char * dst, const char * src, size_t dstsize)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strlcat.c.
 {
     size_t  dstlen;
     size_t  srclen;
     size_t  i;
     dstlen = ft_strlen(dst);
     srclen = ft_strlen(src);
     if (dstlen >= dstsize)
         return (srclen + dstsize);
     i = 0;
     while (i < dstsize - dstlen - 1 && src[i])
     {
         dst[dstlen + i] = src[i];
         i++;
     }
     dst[dstlen + i] = '\0';
     return (srclen + dstlen);
 }
References ft_strlen().
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t maxlen)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strlcpy.c.
 {
     size_t srclen;
     srclen = ft_strlen(src);
     if (srclen + 1 < maxlen)
     {
         ft_memcpy(dst, src, srclen + 1);
     }
     else if (maxlen != 0)
     {
         ft_memcpy(dst, src, maxlen - 1);
         dst[maxlen - 1] = '\0';
     }
     return (srclen);
 }
References ft_memcpy(), and ft_strlen().
ft_strlen()
size_t ft_strlen (const char * s)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strlen.c.
 {
     size_t  i;
     i = 0;
     while (s[i])
         i++;
     return (i);
 }
Referenced by ft_putstr_fd(), ft_strcat(), ft_strclr(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strncat(), ft_strrev(), and ft_strtrim().
ft_strmap()
char* ft_strmap (char const * s, char(*)(char) f)
Applies the function f to each character of the string given as argument to create a fresh new string (with malloc) resulting from the successive applications of f.
Parameters
s The string to map.
f The function to apply to each character of s.
Returns
The fresh string created from the successive applications of f.
Definition at line 24 of file ft_strmap.c.
 {
     char    *s_new;
     size_t  i;
     if (!s || !f)
         return (NULL);
     s_new = ft_strdup(s);
     if (!s_new)
         return (NULL);
     i = 0;
     while (s[i])
     {
         s_new[i] = f(s[i]);
         i++;
     }
     return (s_new);
 }
References ft_strdup().
ft_strmapi()
char* ft_strmapi (char const * s, char(*)(unsigned int, char) f)
Applies the function f to each character of the string passed as argument by giving its index as first argument to create a fresh new string (with malloc) resulting from the successive applications of f.
Parameters
s The string to map.
f The function to apply to each character and its index of s.
Returns
The fresh string created from the successive applications of f.
Definition at line 25 of file ft_strmapi.c.
 {
     char    *s_new;
     size_t  i;
     if (!s || !f)
         return (NULL);
     s_new = ft_strdup(s);
     if (!s_new)
         return (NULL);
     i = 0;
     while (s[i])
     {
         s_new[i] = f(i, s[i]);
         i++;
     }
     return (s_new);
 }
References ft_strdup().
ft_strncat()
char* ft_strncat (char * s1, const char * s2, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strncat.c.
 {
     size_t  i;
     size_t  len;
     i = 0;
     len = ft_strlen(s1);
     while (i < n && s2[i])
     {
         s1[len + i] = s2[i];
         i++;
     }
     s1[len + i] = 0;
     return (s1);
 }
References ft_strlen().
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strncmp.c.
 {
     unsigned char *s1u;
     unsigned char *s2u;
     s1u = (unsigned char *)s1;
     s2u = (unsigned char *)s2;
     while ((*s1u || *s2u) && n-- > 0)
     {
         if (*s1u - *s2u)
             return (*s1u - *s2u);
         s1u++;
         s2u++;
     }
     return (0);
 }
ft_strncpy()
char* ft_strncpy (char * dst, const char * src, size_t len)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strncpy.c.
 {
     size_t  i;
     i = 0;
     while (i < len && src[i])
     {
         dst[i] = src[i];
         i++;
     }
     while (i < len)
     {
         dst[i] = '\0';
         i++;
     }
     return (dst);
 }
Referenced by ft_strsub().
ft_strndup()
char* ft_strndup (const char * s1, size_t len)
Allocate sufficient memory for a string of len characters, do the copy of len characters, NULL terminate the string, and return a pointer to it. The pointer may subsequently be used as an argument to the function free.
Parameters
s1 String to be copied from.
len Number of characters to copy.
Returns
String of length len with copied characters.
Remarks
If s1 contains less than len characters, behaviour is undefined.
Definition at line 27 of file ft_strndup.c.
 {
     size_t  i;
     char    *cpy;
     if (!(cpy = (char *)malloc(sizeof(char) * (len + 1))))
         return (NULL);
     i = 0;
     while (i < len)
     {
         cpy[i] = s1[i];
         i++;
     }
     cpy[i] = '\0';
     return (cpy);
 }
Referenced by ft_strsplit().
ft_strnequ()
int ft_strnequ (char const * s1, char const * s2, size_t n)
Lexicographical comparison between s1 and s2 up to n characters or until a '\0' is reached. If the 2 strings are identical, the function returns 1, or 0 otherwise.
Parameters
s1 The first string to be compared.
s2 The second string to be compared.
n The maximum number of characters to be compared.
Returns
1 or 0 according to if the 2 strings are identical or not.
Definition at line 25 of file ft_strnequ.c.
 {
     if (!s1 && !s2)
         return (1);
     else if (!s1 || !s2)
         return (0);
     while ((*s1 || *s2) && n-- > 0)
     {
         if (*s1 != *s2)
             return (0);
         s1++;
         s2++;
     }
     return (1);
 }
ft_strnew()
char* ft_strnew (size_t size)
Allocates (with malloc) and returns a fresh string ending with '\0'. Each character of the string is initialized at '\0'. If the allocation fails the function returns NULL.
Parameters
size The size of the string to be allocated.
Returns
The string allocated and initialized to 0.
Definition at line 23 of file ft_strnew.c.
 {
     if (size + 1 < size)
         return (NULL);
     return (ft_memalloc(sizeof(char) * (size + 1)));
 }
References ft_memalloc().
Referenced by ft_itoa(), ft_strdup(), ft_strjoin(), ft_strrev(), and ft_strsub().
ft_strnstr()
char* ft_strnstr (const char * haystack, const char * needle, size_t len)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strnstr.c.
 {
     size_t  i;
     size_t  j;
     i = 0;
     if (*needle == '\0')
         return ((char *)haystack);
     while (haystack[i] && i < len)
     {
         if (haystack[i] == needle[0])
         {
             j = 0;
             while (needle[j] &&
                     i + j < len &&
                     haystack[i + j] == needle[j])
                 j++;
             if (needle[j] == 0)
                 return ((char *)(haystack + i));
         }
         i++;
     }
     return (NULL);
 }
ft_strrchr()
char* ft_strrchr (const char * s, int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strrchr.c.
 {
     size_t  i;
     size_t  last;
     int     found;
     i = 0;
     last = 0;
     found = 0;
     while (s[i])
     {
         if (s[i] == c)
         {
             last = i;
             found = 1;
         }
         i++;
     }
     if (found)
         return ((char *)(s + last));
     else if (c == 0)
         return ((char *)(s + i));
     else
         return (NULL);
 }
ft_strrev()
char* ft_strrev (const char * s)
Allocates (with malloc) and returns a reversed NULL-terminated string or NULL if allocation fails.
Example: ft_strrev("0123456789") returns "9876543210"
Parameters
s String to be reversed.
Returns
Reversed string.
Definition at line 24 of file ft_strrev.c.
 {
     size_t  len;
     size_t  i;
     char    *srev;
     if (!s)
         return (NULL);
     len = ft_strlen(s);
     if (!(srev = ft_strnew(len)))
         return (NULL);
     i = 0;
     while (i < len)
     {
         srev[i] = s[len - i - 1];
         i++;
     }
     return (srev);
 }
References ft_strlen(), and ft_strnew().
ft_strsplit()
char** ft_strsplit (char const * s, char delim)
Allocates (with malloc) and returns an array of fresh strings (all ending with '\0', including the array itself) obtained by splitting s using the character c as a delimiter. If the allocation fails the function returns NULL.
Example : ft_strsplit("*hello*fellow***students*", *) returns the array ["hello", "fellow", "students"].
Parameters
s The string to split.
delim The delimiter character.
Returns
The array of fresh strings result of the split.
Definition at line 69 of file ft_strsplit.c.
 {
     char        **tab;
     const char  *start;
     const char  *end;
     size_t      wcount;
     size_t      i;
     wcount = count_words(s, delim);
     if (!(tab = ft_memalloc(sizeof(char *) * (wcount + 1))))
         return (NULL);
     i = 0;
     end = s;
     while (i < wcount)
     {
         start = search_not_delim(end, delim);
         end = search_delim(start, delim);
         if (!(tab[i] = ft_strndup(start, end - start)))
         {
             free_tab(tab);
             return (NULL);
         }
         i++;
     }
     tab[i++] = NULL;
     return (tab);
 }
References ft_memalloc(), and ft_strndup().
ft_strstr()
char* ft_strstr (const char * haystack, const char * needle)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_strstr.c.
 {
     size_t  i;
     size_t  j;
     i = 0;
     if (*needle == 0)
         return ((char *)haystack);
     while (haystack[i])
     {
         if (haystack[i] == needle[0])
         {
             j = 0;
             while (needle[j] && haystack[i + j] == needle[j])
                 j++;
             if (needle[j] == 0)
                 return ((char *)(haystack + i));
         }
         i++;
     }
     return (NULL);
 }
ft_strsub()
char* ft_strsub (char const * s, unsigned int start, size_t len)
Allocates (with malloc) and returns a fresh substring from the string given as argument. The substring begins at index start and is of size len. If start and len arent refering to a valid substring, the behavior is undefined. If the allocation fails, the function returns NULL.
Parameters
s The string from which create the substring.
start The start index of the substring.
len The size of the substring.
Returns
The substring.
Definition at line 27 of file ft_strsub.c.
 {
     char    *sub;
     if (!s ||
         !(sub = ft_strnew(len)))
         return (NULL);
     ft_strncpy(sub, s + start, len);
     return (sub);
 }
References ft_strncpy(), and ft_strnew().
Referenced by ft_strtrim().
ft_strtrim()
char* ft_strtrim (char const * s)
Allocates (with malloc) and returns a copy of the string given as argument without whitespaces at the beginning or at the end of the string. Will be considered as whitespaces the following characters ' ', '\n' and '\t'. If s has no whitespaces at the beginning or at the end, the function returns a copy of s. If the allocation fails the function returns NULL.
Parameters
s The string to be trimmed.
Returns
The fresh trimmed string or a copy of s.
Definition at line 31 of file ft_strtrim.c.
 {
     size_t  i;
     size_t  j;
     i = 0;
     while (is_trimmable(s[i]))
         i++;
     if (s[i] == '\0')
         return (ft_strdup(""));
     j = ft_strlen(s) - 1;
     while (is_trimmable(s[j]))
         j--;
     return (ft_strsub(s, i, j - i + 1));
 }
References ft_strdup(), ft_strlen(), and ft_strsub().
ft_tolower()
int ft_tolower (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_tolower.c.
 {
     if (c >= 'A' && c <= 'Z')
         return (c + 'a' - 'A');
     else
         return (c);
 }
ft_toupper()
int ft_toupper (int c)
Mimic behaviour of a function of the same name (sans ft_) from libc.
Definition at line 19 of file ft_toupper.c.
 {
     if (c >= 'a' && c <= 'z')
         return (c + 'A' - 'a');
     else
         return (c);
 }